#!/bin/sh
#
# Automatically adds branch name to every commit message. 
#

NAME=$(git branch | grep '*' | sed 's/* //') 
TEXT=$(cat "$1" | sed '/^#.*/d')

if [ -n "$TEXT" ]
then
    echo "$NAME"': '$(cat "$1" | sed '/^#.*/d') > "$1"
else
    echo "Aborting commit due to empty commit message."
    exit 1
fi
